
LABEL authors="Pooya"
FROM node:14-alpine

# Set the working directory to /app/frontend
WORKDIR /app/frontend

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the port that your React app will run on
EXPOSE 3000

# Define the command to run your application
CMD ["npm", "start"]